export const bandTeams = [
    {
        id: 1,
        img: "https://i.ibb.co/c6cQrBv/22072lg.jpg",
        title: "Artcell",
        members: 5,
        leader: "Ershad Zaman",
        cost: 70000,
        type: "Metal band",
    },
    {
        id: 2,
        img: "https://i.ibb.co/SyKsQdr/warfaze.png",
        title: "Warfaze",
        members: 6,
        leader: "Sheikh Monirul Alam Tipu",
        cost: 80000,
        type: "Hard Rock band",
    },
    {
        id: 3,
        img: "https://i.ibb.co/N7LFk7p/22493lg.jpg",
        title: "Aurthohin",
        members: 4,
        leader: "Saidus Sumon",
        cost: 85000,
        type: "hard rock and metal band",
    },
    {
        id: 4,
        img: "https://i.ibb.co/bNwgqW1/22496lg.jpg",
        title: "Love Runs Blind (LRB)",
        members: 5,
        leader: "Ayub Bachchu",
        cost: 120000,
        type: "rock band",
    },
    {
        id: 5,
        img: "https://i.ibb.co/CVszckz/22970lg.jpg",
        title: "Shironamhin",
        members: 5,
        leader: " Ziaur Rahman",
        cost: 95000,
        type: "independent mix band",
    },
    {
        id: 6,
        img: "https://i.ibb.co/r2cDPw1/22530lg.jpg",
        title: "Powersurge",
        members: 5,
        leader: "Jamshed Chowdhury",
        cost: 75000,
        type: "American power metal band",
    },
    {
        id: 7,
        img: "https://i.ibb.co/3htf6gB/download-3.jpg",
        title: "Nagar Baul",
        members: 4,
        leader: "James",
        cost: 150000,
        type: "rock band",
    },
    {
        id: 8,
        img: "https://i.ibb.co/XthCZYv/22507lg.jpg",
        title: "Cryptic Fate",
        members: 4,
        leader: "Iresh Zaker",
        cost: 55000,
        type: "metal band",
    },
    {
        id: 9,
        img: "https://i.ibb.co/ZBMbZFS/22508lg.jpg",
        title: "Shunno",
        members: 4,
        leader: "Shaker",
        cost: 58000,
        type: "pop rock band",
    },
];
